service: notiplat-gateway

frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x

  stage: alpha
  region: ap-northeast-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:DeleteMessage"
        - "sqs:GetQueueAttributes"
        - "sqs:ReceiveMessage"
      Resource: "arn:aws:sqs:*"
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
        - "ses:SendTemplatedEmail"
        - "ses:SendCustomVerificationEmail"
      Resource: "arn:aws:ses:*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:ap-northeast-2:*:function:*"
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
      Resource: "arn:aws:logs:ap-northeast-2:*:*"
    - Effect: "Allow"
      Action:
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:ap-northeast-2:*:log-group:/aws/lambda/*:*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  email:
    handler: bin/email-gw
    events:
      - sqs: ${ssm:/finfech/alpha/notiplat/emailgw/arn}
  sms:
    handler: bin/sms-gw
    events:
      - sqs: ${ssm:/finfech/alpha/notiplat/smsgw/arn}
  smsme:
    handler: bin/smsme-gw
    environment:
      IFTTT_KEY: ${ssm:/finfech/alpha/notiplat/smsmegw/ifttt_key~true}
    events:
      - sqs: ${ssm:/finfech/alpha/notiplat/smsmegw/queue_arn}
