on: [push]
name: Actions CI Workflow
env:
  BUILD_VERSION: b${{ github.run_id }}
jobs:
  "Build":
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t notiplat-gateway .  

      - run: docker save notiplat-gateway > image.tar

      - uses: actions/upload-artifact@v1
        with:
          name: docker-image-tar
          path: image.tar
  "Push":
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - "Build"  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: docker-image-tar

      - name: Load docker image
        run: docker load --input docker-image-tar/image.tar

      - name: Tag docker image
        run: docker tag notiplat-gateway 223040942478.dkr.ecr.ap-northeast-2.amazonaws.com/notiplat-gateway:$BUILD_VERSION

      - name: Login ECR
        run: aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 223040942478.dkr.ecr.ap-northeast-2.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Push docker image
        run: docker push 223040942478.dkr.ecr.ap-northeast-2.amazonaws.com/notiplat-gateway:$BUILD_VERSION